
---

# storage stage - dynamic-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: console-pvc
  namespace: @@NAME_NS@@ 
spec:
  storageClassName: csi-cephfs-sc 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
# console-operator stage 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: @@NAME_NS@@
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --pwd=/var/tmp/configs/
        # - --namespace=console-system
        image: tmaxcloudck/console-operator:@@VER@@
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /var/tmp/configs
          name: dynamic-config
      serviceAccountName: @@NAME_NS@@-admin
      terminationGracePeriodSeconds: 10
      volumes:
      - name: dynamic-config 
        persistentVolumeClaim:
          claimName: console-pvc
