# permissions for end users to view consoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: console-viewer-role
rules:
- apiGroups:
  - hypercloud.tmaxcloud.com
  resources:
  - consoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypercloud.tmaxcloud.com
  resources:
  - consoles/status
  verbs:
  - get
