# apiVersion: v1
# kind: Namespace 
# metadata:
#   name: default

# ---

apiVersion: hypercloud.tmaxcloud.com/v1
kind: Console
metadata:
  name: hc-console1
spec:
  app: 
    repository: "tmaxcloudck/hypercloud-console"
    tag: "4.2.0.0"
    replicas: 1
    serviceType: "NodePort"
  configuration:
    routers:
      show:
        server: "http://192.168.8.62:9002/"
        rule: "Host(`console`) && PathPrefix(`/console/`)"
        path: "/console/"
      cpd:
        server: "http://cpdch.org/"
        rule: "Host(`cpdch.org`) && PathPrefix(`/cpd/`)"
        path: "/cpd/"
      naver:
        server: "https://www.naver.com/"
        rule: "Host(`naver.com`) && PathPrefix(`/naver/`)"
        path: "/naver/"
      daum:
        server: "https://www.daum.com/"
        rule: "Host(`daum.com`) && PathPrefix(`/daum/`)"
        path: "/daum/"
      google:
        server: "https://google.com/"
        rule: "Host(`google.com`) && PathPrefix(`/google/`)"
        path: "/google/"