# apiVersion: v1
# kind: Namespace 
# metadata:
#   name: default

# ---

apiVersion: hypercloud.tmaxcloud.com/v1
kind: Console
metadata:
  name: console-v35
spec:
  app: 
    repository: "tmaxcloudck/hypercloud-console"
    tag: "4.2.0.0"
    replicas: 1
    serviceType: "NodePort"

