apiVersion: hypercloud.tmaxcloud.com/v1
kind: Console
metadata:
  name: console-sample
  namespace: default
spec:
  app: 
    repository: "tmaxcloudck/hypercloud-console"
    tag: "4.2.0.0"
    replicas: 2
    serviceType: "NodePort"
