# apiVersion: v1
# kind: Namespace 
# metadata:
#   name: default

# ---

apiVersion: hypercloud.tmaxcloud.com/v1
kind: Console
metadata:
  name: hc-console
  namespace: console-system
spec:
  configuration:
    routers:
      f-test-2ddsb:
        path: /api/f-test-2ddsb/
        rule: PathPrefix(`/api/f-test-2ddsb/`)
        server: https://f-test-2ddsb-apiserver-492352234.us-east-2.elb.amazonaws.com:6443
      jmc-zgw2v:
        path: /api/jmc-zgw2v/
        rule: PathPrefix(`/api/jmc-zgw2v/`)
        server: https://jmc-zgw2v-apiserver-1390659011.ap-northeast-2.elb.amazonaws.com:6443
      master:
        path: /api/master/
        rule: PathPrefix(`/api/master/`)
        server: https://220.90.208.100:6443
      sh-test-us-east1:
        path: /api/sh-test-us-east1/
        rule: PathPrefix(`/api/sh-test-us-east1/`)
        server: https://sh-test-us-east1-apiserver-1962929540.us-east-1.elb.amazonaws.com:6443