# apiVersion: v1
# kind: Namespace 
# metadata:
#   name: default

# ---

apiVersion: hypercloud.tmaxcloud.com/v1
kind: Console
metadata:
  name: hc-console1
  namespace: kube-system
spec:
  configuration:
    routers:
      test:
        server: "http://192.168.8.62:9002/"
        rule: "Host(`console`) && PathPrefix(`/console/`)"
        path: "/console/"
      naver:
        server: "https://www.naver.com/"
        rule: "Host(`naver.com`) && PathPrefix(`/naver/`)"
        path: "/naver/"
      daum:
        server: "https://www.daum.com/"
        rule: "Host(`daum.com`) && PathPrefix(`/daum/`)"
        path: "/daum/"